/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dashboard_hebergement (void);
GtkWidget* create_af_alarme (void);
GtkWidget* create_af_hebergement (void);
GtkWidget* create_mod_hebergement (void);
GtkWidget* create_aj_hebergement (void);
GtkWidget* create_recherche (void);
GtkWidget* create_a_inscription (void);
GtkWidget* create_a_connexion (void);
GtkWidget* create_a_admin (void);
GtkWidget* create_a_suppression (void);
GtkWidget* create_a_modif (void);
GtkWidget* create_ad_modif (void);
GtkWidget* create_adminaffiche (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_affiche (void);
GtkWidget* create_fenetre_modif (void);
GtkWidget* create_tache2 (void);
GtkWidget* create_fenetre_ajout1 (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_nb_etudiants (void);
GtkWidget* create_checkin (void);
GtkWidget* create_AjoutRepas (void);
GtkWidget* create_HomeRepas (void);
GtkWidget* create_UpdateRepas (void);
GtkWidget* create_dash (void);
GtkWidget* create_auth_ (void);
GtkWidget* create_inscri_ (void);
